### PR TITLE
Improve how wheels are extracted

### PR DESCRIPTION
**Pull request by takluyver**
Closes gh-77

@cachitas, this should fix the issue with opencv, if you have time to test.

### CODE REVIEW

**Comment by cachitas** [comment]
This works for me. The cv2 is correctly extracted from `opencv-python`.

**Comment by takluyver** [comment]
Thanks, I'll merge this, then.

Did you want to do a PR to add some logging when it gets a wheel from the cache?

**Comment by cachitas** [comment]
I'm sure you can add that in a blink of an eye, so feel free to go for it.

I'm working on a branch for the examples and this branching for new feature, staging, upstream sync, etc still confuses me a bit. Nevertheless, if you leave that for me, I can address it later on. I believe it is just a matter of finding the right spot to log that info and test it.

**Comment by takluyver** [comment]
Great, I'll add a bit of logging and let you carry on with the examples. Git is rather fiddly - I periodically forget to make a branch before committing, and then have to remember how to clean it up.

**Pull request merged**
